module.exports = {
    beforeEach: browser => {
        browser.url('https://devmountain-qa.github.io/employee-manager/1.2_Version/index.html')
            .waitForElementPresent('body', 8000)
            .verify.urlContains("https://devmountain-qa.github.io/employee-manager/1.2_Version/index.html")
            .waitForElementVisible('.main-container')
    },
    after: browser => {
        browser.end()
    },
    'Check for change, save, and cancel button. Change, Save, and cancel all entries': browser => {
        var employee1 = {
            Name: 'Ortiz Barnie',
            Phone: '1234567890',
            Title: 'OEC'
        } //you can also declare this above module.exports

        browser
            .click('[name="employee1"]')
            .clearValue('[name="nameEntry"]')
            .setValue('[name="nameEntry"]', employee1.Name)
            .clearValue('[name="phoneEntry"]')
            .setValue('[name="phoneEntry"]', employee1.Phone)
            .clearValue('[name="titleEntry"]')
            .setValue('[name="titleEntry"]', employee1.Title)
            .click('[name="save"]')
            .verify.value('[name="nameEntry"]', employee1.Name)
            .verify.value('[name="phoneEntry"]', employee1.Phone)
            .verify.value('[name="titleEntry"]', employee1.Title)
            .clearValue('[name="nameEntry"]')
            .setValue('[name="nameEntry"]', 'Ortie')
            .clearValue('[name="phoneEntry"]')
            .setValue('[name="phoneEntry"]', '123890')
            .clearValue('[name="titleEntry"]')
            .setValue('[name="titleEntry"]', 'OECCOE')
            .click('[name="cancel"]')
            .verify.value('[name="nameEntry"]', employee1.Name)
            .verify.value('[name="phoneEntry"]', employee1.Phone)
            .verify.value('[name="titleEntry"]', employee1.Title)

            .click('[name="employee2"]')
            .clearValue('[name="nameEntry"]')
            .setValue('[name="nameEntry"]', 'Barn Man')
            .clearValue('[name="phoneEntry"]')
            .setValue('[name="phoneEntry"]', '2637849863')
            .clearValue('[name="titleEntry"]')
            .setValue('[name="titleEntry"]', 'OTTC')
            .click('[name="save"]')
            .verify.value('[name="nameEntry"]', "Barn Man")
            .verify.value('[name="phoneEntry"]', "2637849863")
            .verify.value('[name="titleEntry"]', "OTTC")
            .clearValue('[name="nameEntry"]')
            .setValue('[name="nameEntry"]', 'man')
            .clearValue('[name="phoneEntry"]')
            .setValue('[name="phoneEntry"]', 'yolo')
            .clearValue('[name="titleEntry"]')
            .setValue('[name="titleEntry"]', 'haha')
            .click('[name="cancel"]')
            .verify.value('[name="nameEntry"]', "Barn Man")
            .verify.value('[name="phoneEntry"]', "2637849863")
            .verify.value('[name="titleEntry"]', "OTTC")

            .click('[name="employee3"]')
            .clearValue('[name="nameEntry"]')
            .setValue('[name="nameEntry"]', 'Weaver PHILY')
            .clearValue('[name="phoneEntry"]')
            .setValue('[name="phoneEntry"]', '8755473849')
            .clearValue('[name="titleEntry"]')
            .setValue('[name="titleEntry"]', 'GerMan')
            .click('[name="save"]')
            .verify.value('[name="titleEntry"]', "GerMan")
            .verify.value('[name="phoneEntry"]', "8755473849")
            .verify.value('[name="nameEntry"]', "Weaver PHILY")
            .clearValue('[name="nameEntry"]')
            .setValue('[name="nameEntry"]', 'man')
            .clearValue('[name="phoneEntry"]')
            .setValue('[name="phoneEntry"]', 'yolo')
            .clearValue('[name="titleEntry"]')
            .setValue('[name="titleEntry"]', 'haha')
            .click('[name="cancel"]')
            .verify.value('[name="nameEntry"]', "Weaver PHILY")
            .verify.value('[name="phoneEntry"]', "8755473849")
            .verify.value('[name="titleEntry"]', "GerMan")

            .click('[name="employee4"]')
            .clearValue('[name="nameEntry"]')
            .setValue('[name="nameEntry"]', 'Osbone T-bone')
            .clearValue('[name="phoneEntry"]')
            .setValue('[name="phoneEntry"]', '8376453674')
            .clearValue('[name="titleEntry"]')
            .setValue('[name="titleEntry"]', 'Eng DD')
            .click('[name="save"]')
            .verify.value('[name="titleEntry"]', "Eng DD")
            .verify.value('[name="phoneEntry"]', "8376453674")
            .verify.value('[name="nameEntry"]', "Osbone T-bone")


            .click('[name="employee5"]')
            .clearValue('[name="nameEntry"]')
            .setValue('[name="nameEntry"]', 'BER Dollie')
            .clearValue('[name="phoneEntry"]')
            .setValue('[name="phoneEntry"]', '9876543456')
            .clearValue('[name="titleEntry"]')
            .setValue('[name="titleEntry"]', 'Front Dev')
            .click('[name="save"]')
            .verify.value('[name="titleEntry"]', "Front Dev")
            .verify.value('[name="phoneEntry"]', "9876543456")
            .verify.value('[name="nameEntry"]', "BER Dollie")


            .click('[name="employee6"]')
            .clearValue('[name="nameEntry"]')
            .setValue('[name="nameEntry"]', 'Will Harry')
            .clearValue('[name="phoneEntry"]')
            .setValue('[name="phoneEntry"]', '0987656789')
            .clearValue('[name="titleEntry"]')
            .setValue('[name="titleEntry"]', 'Dev Fronty')
            .click('[name="save"]')
            .verify.value('[name="titleEntry"]', "Dev Fronty")
            .verify.value('[name="phoneEntry"]', "0987656789")
            .verify.value('[name="nameEntry"]', "Will Harry")


            .click('[name="employee7"]')
            .clearValue('[name="nameEntry"]')
            .setValue('[name="nameEntry"]', 'Estrada Rude man')
            .clearValue('[name="phoneEntry"]')
            .setValue('[name="phoneEntry"]', '7836746356')
            .clearValue('[name="titleEntry"]')
            .setValue('[name="titleEntry"]', 'Back Dev')
            .click('[name="save"]')
            .verify.value('[name="titleEntry"]', "Back Dev")
            .verify.value('[name="phoneEntry"]', "7836746356")
            .verify.value('[name="nameEntry"]', "Estrada Rude man")


            .click('[name="employee8"]')
            .clearValue('[name="nameEntry"]')
            .setValue('[name="nameEntry"]', 'White Louis')
            .clearValue('[name="phoneEntry"]')
            .setValue('[name="phoneEntry"]', '9878976432')
            .clearValue('[name="titleEntry"]')
            .setValue('[name="titleEntry"]', 'Full Dev')
            .click('[name="save"]')
            .verify.value('[name="titleEntry"]', "Full Dev")
            .verify.value('[name="phoneEntry"]', "9878976432")
            .verify.value('[name="nameEntry"]', "White Louis")


            .click('[name="employee9"]')
            .clearValue('[name="nameEntry"]')
            .setValue('[name="nameEntry"]', 'Sparky Eve')
            .clearValue('[name="phoneEntry"]')
            .setValue('[name="phoneEntry"]', '7867564567')
            .clearValue('[name="titleEntry"]')
            .setValue('[name="titleEntry"]', 'Manage Product person')
            .click('[name="save"]')
            .verify.value('[name="titleEntry"]', "Manage Product person")
            .verify.value('[name="phoneEntry"]', "7867564567")
            .verify.value('[name="nameEntry"]', "Sparky Eve")


            .click('[name="employee10"]')
            .clearValue('[name="nameEntry"]')
            .setValue('[name="nameEntry"]', 'Brewer Person')
            .clearValue('[name="phoneEntry"]')
            .setValue('[name="phoneEntry"]', '0909878786')
            .clearValue('[name="titleEntry"]')
            .setValue('[name="titleEntry"]', 'Manage Sales man')
            .click('[name="save"]')
            .verify.value('[name="titleEntry"]', "Manage Sales man")
            .verify.value('[name="phoneEntry"]', "0909878786")
            .verify.value('[name="nameEntry"]', "Brewer Person")


    },
    'Add Employee': browser => {
        browser
            .click('[name="addEmployee"]')
            .click('[name="employee11"]')
            .clearValue('[name="nameEntry"]')
            .setValue('[name="nameEntry"]', 'Person funny')
            .clearValue('[name="phoneEntry"]')
            .setValue('[name="phoneEntry"]', '8907654567')
            .clearValue('[name="titleEntry"]')
            .setValue('[name="titleEntry"]', 'Jobless')
            .click('[name="save"]')
            .verify.value('[name="titleEntry"]', "Jobless")
            .verify.value('[name="phoneEntry"]', "8907654567")
            .verify.value('[name="nameEntry"]', "Person funny")

            .click('[name="addEmployee"]')
            .click('[name="employee12"]')
            .clearValue('[name="nameEntry"]')
            .setValue('[name="nameEntry"]', 'Crazy dude')
            .clearValue('[name="phoneEntry"]')
            .setValue('[name="phoneEntry"]', '8374657686')
            .clearValue('[name="titleEntry"]')
            .setValue('[name="titleEntry"]', 'Has one Job')
            .click('[name="save"]')
            .verify.value('[name="titleEntry"]', "Has one Job")
            .verify.value('[name="phoneEntry"]', "8374657686")
            .verify.value('[name="nameEntry"]', "Crazy dude")

    },
    'Check for errors': browser => {
        browser
            .click('[name="employee1"]')
            .clearValue('[name="nameEntry"]')
            .setValue('[name="nameEntry"]', 'Ortiz Barniejfisla;jifdl;aisjdifl;dsajifd')
            .clearValue('[name="phoneEntry"]')
            .setValue('[name="phoneEntry"]', '1234567890sdajfildsa')
            .clearValue('[name="titleEntry"]')
            .setValue('[name="titleEntry"]', '12C382938@#$#@EWF')
            .click('[name="save"]')
            .verify.visible(".errorCard")
            .verify.elementPresent(".invalidInfo")
            .verify.elementNotPresent(".hidden")
            .click('[name="cancel"]')
            .verify.elementPresent(".hidden")
            .verify.elementNotPresent(".invalidInfo")
    },
    'no entry errors': browser => {
        browser
            .click('[name="employee1"]')
            .clearValue('[name="nameEntry"]')
            .setValue('[name="nameEntry"]', '')
            .clearValue('[name="phoneEntry"]')
            .setValue('[name="phoneEntry"]', ' ')
            .clearValue('[name="titleEntry"]')
            .setValue('[name="titleEntry"]', '')
            .click('[name="save"]')
            .verify.visible(".errorCard")
            .verify.elementPresent(".invalidInfo")
            .verify.elementNotPresent(".hidden")
            .click('[name="cancel"]')
            .verify.elementPresent(".hidden")
            .verify.elementNotPresent(".invalidInfo")

    }

}