module.exports = [
    {
        loan: 'Home Purchase',
        checkLoan: 'Home',
        property: 'Single Family Home',
        checkProperty: 'Single Family Home',
        city: "indiana",
        house: 'secondary',
        checkHouse: 'Secondary',
        home: 'yes',
        checkHome: 'True',
        agent: 'no',
        checkAgent: 'False',
        price: '100',
        down: '10',
        score: 'excellent',
        checkScore: 'Excellent',
        bank: 'both',
        address1: '211 skyline dr',
        address2: '',
        address3: 'Indiana, PA 15701',
        first: 'Daniel',
        last: 'Peng',
        email: 'daniel@yahoo.com',
    },
    {
        loan: 'Home Equity loan/line',
        checkLoan: 'Home Equity',
        property: 'Condo',
        checkProperty: 'Condo',
        city: "indiana",
        house: 'rental',
        checkHouse: 'Rental',
        home: 'yes',
        checkHome: 'True',
        agent: 'yes',
        checkAgent: 'True',
        price: '500',
        down: '30',
        score: 'fair',
        checkScore: 'Fair',
        bank: 'foreclosure',
        address1: '211 skyline dr',
        address2: '',
        address3: 'Indiana, PA 15701',
        first: 'Jack',
        last: 'Daniels',
        email: 'Jack@yahoo.com',
    },
    {
        loan: 'Refinance',
        checkLoan: 'Refinance',
        property: 'Townhome',
        checkProperty: 'Town Home',
        city: "indiana",
        house: 'primary',
        checkHouse: 'Primary',
        home: 'no',
        checkHome: 'False',
        agent: 'yes',
        checkAgent: 'True',
        price: '1000',
        down: '100',
        score: 'good',
        checkScore: 'Good',
        bank: 'bankruptcy',
        address1: '211 skyline dr',
        address2: '',
        address3: 'Indiana, PA 15701',
        first: 'Funny',
        last: 'Person',
        email: 'FP@yahoo.com',
    }
]